config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :property_owners

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :properties, only: [:show] do
    get 'search', on: :collection
    resources :price_ranges, only: [:create, :new, :show]
    resources :proposals, only: [:new, :create, :index] do
      post 'accepted', to: 'proposals#accepted'
      post 'reject', to: 'proposals#reject'
    end
  end

  scope :property_owners do
    resources :properties, only: [:index, :show, :new, :create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :proposals, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price_range.rb
class PriceRange < ApplicationRecord
  belongs_to :property
  validates :description, :start_date, :end_date, :daily_rate,
      presence: { message: 'É necessário preencher todos os dados da temporada'}

  validate :final_date_is_greater_than_start_date, on: :create

  def final_date_is_greater_than_start_date
    if start_date && end_date && start_date > end_date
      errors[:base] << 'A data inicial não pode ser maior que a data final'
    end
  end
end

app/models/property.rb
  class Property < ApplicationRecord
  has_attached_file :main_photo, styles: {thumb: '100X100', medium: '300x300'}

  belongs_to :property_location
  belongs_to :property_owner

  has_many :price_ranges
  has_many :proposals

  validates :main_photo, attachment_presence: true
  validates_attachment_content_type :main_photo, content_type: /\Aimage\/.*\z/
  validates :title, :maximum_guests, :minimum_rent, :maximum_rent, :daily_rate,
    :rent_purpose, :description, :neighborhood, :rooms, presence: {
      message: 'É necessário preencher todos os dados do imóvel' }
end

app/models/property_location.rb
class PropertyLocation < ApplicationRecord
  has_many :properties
end

app/models/property_owner.rb
class PropertyOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :property
  belongs_to :user
  validates :rent_purpose, :total_guest,
            :start_date, :end_date, presence: true

  enum status: %i[pending accepted rejected]
  before_save :calculate_total_amount

  private

  def calculate_total_amount
    sum = 0
    days = (start_date..end_date).to_a.length

    (start_date..end_date).each do |day|
      unless property.price_ranges.empty?
        property.price_ranges.each do |range|
          if (
            range.start_date.to_date..range.end_date.to_date
          ).to_a.include? day.to_date
            sum += range.daily_rate
            days -= 1
          end
        end
      end
    end

    sum += days * property.daily_rate
    self.total_amount = sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :proposals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.order(created_at: :desc).last(10)

    if @properties.empty?
      flash[:alert] = "Não existe nenhum imóvel cadastrado no momento"
    end
  end
end

app/controllers/price_ranges_controller.rb
class PriceRangesController < ApplicationController
  def new
    @property = Property.find_by(id: params[:property_id])
    @price_range = PriceRange.new
  end

  def create
    create_params = params.require(:price_range).permit(:description,
                      :start_date, :end_date, :daily_rate, :property_id
                    )

    @property = Property.find(params[:property_id])
    @price_range = @property.price_ranges.build(create_params)

    if @price_range.save
      redirect_to property_path @property
    else
      render :new
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_property_owner!, only: [:new, :create]

  def search
    @properties = Property.where(property_location_id: params[:q])

    if @properties.empty?
      flash[:alert] = 'Nenhum resultado encontrado'
    end
  end

  def show
    @property = Property.find_by(id: params[:id])
    if @property.nil?
      redirect_to root_path
    else
      @proposals = @property.proposals.where.not(status: :rejected)
    end
  end

  def new
    @property = Property.new
    @locations = PropertyLocation.all
  end

  def create
    property_params = params.require(:property).permit(:title,:maximum_guests,
                        :maximum_rent, :minimum_rent, :daily_rate, :rent_purpose,
                        :property_location_id, :description, :neighborhood,
                        :accessibility, :allow_pets, :allow_smokers, :rooms,
                        :main_photo, :property_owner_id
                      )

    @property = Property.new(property_params)
    @property.property_owner = current_property_owner

    if @property.save
      redirect_to @property
    else
      @locations = PropertyLocation.all
      render :new
    end
  end

  def index
    @properties = current_property_owner.properties

    if @properties.empty?
      flash[:alert] = 'Você não possui propriedades cadastrada'
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def accepted
    proposal = Proposal.find_by(id: params[:proposal_id])
    proposal.accepted!
    flash[:notice] = 'Proposta aceita com sucesso!'

    redirect_to property_path(proposal.property)
  end

  def create
    proposal_params = params.require(:proposal).permit(
                        :rent_purpose, :total_guest,:start_date, :end_date,
                        :pet, :smoker, :total_amount, :details, :property_id,
                        :user_id
                      )

    @property = Property.find(params[:property_id])
    @proposal = Proposal.new(proposal_params)
    @proposal.property = @property
    @proposal.user = current_user

    if @proposal.save
      flash[:notice] = 'Sua proposta foi enviada com sucesso!'
      redirect_to user_proposals_path(current_user)
    else
      flash[:errors] = 'Não foi possível envia sua proposta!'
      render :new
    end
  end

  def index
    if property_owner_signed_in?
      @proposals = Proposal.where(property_id: params[:property_id])

      if @proposals.empty?
        flash[:alert] = 'Seu imóvel ainda não recebeu nenhuma proposta'
      end
    end

    if user_signed_in?
      @proposals = current_user.proposals

      if @proposals.empty?
        flash[:alert] = 'Você ainda não fez nenhuma proposta para locação'
      end
    end
  end

  def new
    @property = Property.find(params[:property_id])
    @proposal = Proposal.new
  end

  def reject
    Proposal.find(params[:proposal_id]).rejected!
    redirect_to property_path(params[:property_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.photo.file?
      current_user.photo.url(:medium)
    else
      current_user.photo.options[:default_url]
    end
  end

  def edit
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to user
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Bem vindo ao Aluga Temporada</h1>
<%= form_tag(search_properties_path, method: 'get') do %>
  <%= label_tag(:q, "Localização") %>
  <%= select_tag(:q, options_for_select(PropertyLocation.all.map{|l| [l.name, l.id]})) %>
  <%= submit_tag "Filtrar" %>
<% end %>

<%= render partial: 'shared/property', collection: @properties %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlugaTemporada</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/messages'%>
    <%= yield %>
  </body>
</html>

app/views/price_ranges/new.html.erb
<%= render partial: 'shared/model_errors', locals: { model: @price_range } %>

<%= form_for([@property, @price_range]) do |f| %>
  <div>
    <%= f.label :description, 'Nome' %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :start_date, 'Data inicial' %>
    <%= f.text_field :start_date %>
  </div>

  <div>
    <%= f.label :end_date, 'Data final' %>
    <%= f.text_field :end_date %>
  </div>

  <div>
    <%= f.label :daily_rate, 'Preço da diária' %>
    <%= f.text_field :daily_rate %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/properties/_form.html.erb
<%= render partial: 'shared/model_errors', locals: { model: @property } %>

<%= form_for(@property) do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :property_location_id, 'Localização' %>
    <%= f.collection_select(:property_location_id, @locations, :id, :name) %>
  </div>
  <div>
    <%= f.label :neighborhood, 'Bairro' %>
    <%= f.text_field :neighborhood %>
  </div>
  <div>
    <%= f.label :main_photo, 'Foto principal' %>
    <%= f.file_field :main_photo %>
  </div>
  <div>
    <%= f.label :rooms, 'Quantidade de cômodos' %>
    <%= f.number_field :rooms %>
  </div>
  <div>
    <%= f.label :rent_purpose, 'Finalidade' %>
    <%= f.text_field :rent_purpose %>
  </div>
  <div>
    <%= f.label :maximum_guests, 'Máximo de pessoas' %>
    <%= f.number_field :maximum_guests %>
  </div>
  <div>
    <%= f.label :minimum_rent, 'Mínimo de dias para locação' %>
    <%= f.number_field :minimum_rent %>
  </div>
  <div>
    <%= f.label :maximum_rent, 'Máximo de dias para locação' %>
    <%= f.number_field :maximum_rent %>
  </div>
  <div>
    <%= f.label :daily_rate, 'Preço da diária' %>
    <%= f.text_field :daily_rate %>
  </div>
  <div>
    <h3>Condições permitidas</h3>
    <%= f.check_box(:accessibility) %>
    <%= f.label :accessibility, 'Possui acessibilidade' %>
    <br>
    <%= f.check_box(:allow_pets) %>
    <%= f.label :allow_pets, 'Aceita animais' %>
    <br>
    <%= f.check_box(:allow_smokers) %>
    <%= f.label :allow_smokers, 'Aceita fumantes' %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/properties/index.html.erb
<%= render partial: 'shared/property', collection: @properties %>

app/views/properties/new.html.erb
<h1>Cadastrar imóvel</h1>
<%= render 'form' %>
<%= link_to 'Voltar', root_path %>

app/views/properties/search.html.erb
<% @properties.each do |property| %>
  <%= render partial: 'shared/property', locals: {property: property} %>
<% end %>
<p><%= link_to 'Voltar', root_path %></p>

app/views/properties/show.html.erb
<h1><%= @property.title %></h1>
<h3>Descrição:</h3>
<p><%= @property.description %></p>
<ul>
  <li>Localização: <%= @property.property_location.name %></li>
  <li>Bairro: <%= @property.neighborhood %></li>
  <li>Finalidade: <%= @property.rent_purpose %></li>
  <li>Foto principal: <%= image_tag @property.main_photo.url(:medium) %></li>
  <li>Cômodos: <%= @property.rooms %></li>
  <li>Máximo de pessoas: <%= @property.maximum_guests %></li>
  <li>Mínimo de dias: <%= @property.minimum_rent %></li>
  <li>Máximo de dias: <%= @property.maximum_rent %></li>
  <li>Preço da diária: R$ <%= @property.daily_rate %></li>
</ul>
<h3>Condições permitidas:</h3>
<ul>
  <li>Acessibilidade? <%= @property.accessibility? ? 'Sim' : 'Não' %></li>
  <li>Aceita animais? <%= @property.allow_pets? ? 'Sim' : 'Não' %></li>
  <li>Aceita fumantes? <%= @property.allow_smokers? ? 'Sim' : 'Não' %></li>
</ul>

<h3>Preços por temporada</h3>
<% @property.price_ranges.each do |price_range| %>

  <h4><%= price_range.description %></h4>
  <ul>
    <li>Data inicial: <%= price_range.start_date.strftime("%d/%m/%Y") %></li>
    <li>Data final: <%= price_range.end_date.strftime("%d/%m/%Y") %></li>
    <li>Preço da diária: R$ <%= price_range.daily_rate %></li>
  </ul>
<% end %>

<% if @property.property_owner == current_property_owner %>
  <h3> Propostas </h3>
  <% @proposals.each do |proposal| %>
    <%= render partial: "shared/proposal", locals: { proposal: proposal } %>
  <% end %>

  <p><%= link_to 'Cadastrar uma temporada', new_property_price_range_path(@property) %></p>
<% end%>

<% if user_signed_in? %>
  <p><%= link_to 'Enviar uma proposta', new_property_proposal_path(@property) %></p>
<% end%>

<p><%= link_to 'Voltar', root_path %></p>

app/views/property_owners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/proposals/index.html.erb
<h1>Minhas propostas</h1>

<% @proposals.each do |proposal| %>
  <%= render partial: "shared/proposal", locals: {proposal: proposal} %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/proposals/new.html.erb
<%= render partial: 'shared/model_errors', locals:{ model: @proposal } %>

<%= form_for([@property, @proposal]) do |f| %>
  <div>
    <%= f.label :rent_purpose, 'Finalidade da proposta' %>
    <%= f.text_field :rent_purpose %>
  </div>
  <div>
    <%= f.label :total_guest, 'Quantidade de hospedes' %>
    <%= f.number_field :total_guest  %>
  </div>
  <div>
    <%= f.label :start_date, 'Data de entrada' %>
    <%= f.text_field :start_date  %>
  </div>
  <div>
    <%= f.label :end_date, 'Data de saída' %>
    <%= f.text_field :end_date  %>
  </div>
  <div>
    <%= f.label :pet, 'Pretende levar pets?' %>
    <%= f.check_box :pet  %>
  </div>
  <div>
    <%= f.label :smoker, 'Fumante?' %>
    <%= f.check_box :smoker %>
  </div>
  <div>
    <%= f.label :details, 'Mais informações' %>
    <%= f.text_field :details  %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/shared/_messages.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>
<%= flash[:errors] %>

app/views/shared/_model_errors.html.erb
<% model.errors.full_messages.each do |msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <% if property_owner_signed_in? %>
    <p>
      <%= "Olá #{current_property_owner.email}" %> |
      <%= link_to('Sair', destroy_property_owner_session_path, method: :delete)  %>
    </p>
    <%= link_to 'Minhas propriedades', properties_path(current_property_owner) %> |
    <%= link_to 'Cadastrar nova propriedade', new_property_path %>
  <% elsif !user_signed_in? %>
    <%= link_to('Entrar como proprietário', new_property_owner_session_path)  %> |
  <% end %>

  <% if user_signed_in? %>
    <p>
      <%= "Olá #{current_user.email}" %> |
      <%= link_to('Meu perfil', user_path(current_user)) %> |
      <%= link_to('Sair', destroy_user_session_path, method: :delete) %>
    </p>
    <%= link_to 'Minhas propostas', user_proposals_path(current_user) %>
  <% elsif !property_owner_signed_in? %>
    <%= link_to('Entrar como usuário', new_user_session_path) %>
  <% end %>
</nav>
<hr>

app/views/shared/_property.html.erb
<div>
  <h1><%= link_to property.title, property_path(property) %></h1>
  <div><%= image_tag property.main_photo.url(:thumb) %></div>
  <p>Localização: <%= property.property_location.name %></p>
  <p>Valor base: <%= property.daily_rate %>
  <p>Número máximo de hospedes: <%= property.maximum_guests %></p>
  <%= link_to 'Ver mais detalhes', property_path(property) %>
</div>
<div>
  <% if property.property_owner == current_property_owner %>
    <%= link_to 'Visualizar propostas', property_proposals_path(property) %>
  <% end %>
</div>

app/views/shared/_proposal.html.erb
<h2>Imóvel: <%= proposal.property.title %></h2>
<ul>
  <li>Localização: <%= proposal.property.property_location.name %></li>
  <li>Proponente: <%= proposal.user.name %></li>
  <li>Email do proponente: <%= proposal.user.email %></li>
  <li>Telefone do proponete: <%= proposal.user.phone%></li>
  <li>Finalidade da proposta: <%= proposal.rent_purpose %></li>
  <li>Quantidade de hospedes: <%= proposal.total_guest %></li>
  <li>Estadia de <%= proposal.start_date.strftime('%d/%m/%Y') %> até <%= proposal.end_date.strftime('%d/%m/%Y') %></li>
  <li><%= proposal.pet ? 'Vou levar meu pet' : 'Não vou levar o meu pet' %></li>
  <li><%= proposal.smoker ? 'Sou fumante' : 'Não sou fumante' %></li>
  <li>Valor total da proposta: <%= number_to_currency(proposal.total_amount, unit: "R$", separator: ",", delimiter: "") %></li>
  <li>Maiores detalhes: <%= proposal.details %></li>
</ul>

<div id="proposal_<%= proposal.id %>">
  <%= link_to 'Aceitar', property_proposal_accepted_path(proposal.property, proposal), method: :post %>
  <%= link_to 'Rejeitar proposta', property_proposal_reject_path(proposal.property, proposal), method: :post %>
</div>

app/views/users/edit.html.erb
<h1>Meu perfil</h1>
<%= form_for current_user, html: { multipart: true } do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :phone, 'Telefone' %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :photo, 'Minha foto' %>
    <%= f.file_field :photo %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Meu perfil</h1>
<div>
  <%= image_tag current_user.photo.url(:medium) %>
</div>
<ul>
  <li>Nome: <%= current_user.name %></li>
  <li>Email: <%= current_user.email %></li>
  <li>Telefone: <%= current_user.phone %></li>
</ul>
<%= link_to 'Editar perfil', edit_user_path(current_user) %>
<p>
  <%= link_to 'Voltar', root_path %>
</p>